name: CI

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

    workflow_dispatch:

jobs:
    build:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
                file: [example.cpp, cppbits_source.cpp]

        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v3

            - name: Build example
              run: g++ -o test ${{ matrix.file }} -I.

            - name: Run example
              run: ./test